apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: dev
type: Opaque
stringData:
  # Das Passwort für den PostgreSQL-Container
  POSTGRES_PASSWORD: "psgres_db"
  
  # Der Schlüssel für die JWT-Tokens (Login)
  SECRET_KEY: "fastapi_liora_26"
  
  # Die komplette Verbindungs-URL (WICHTIG: Hier muss das Passwort drinstehen!)
  DATABASE_URL: "postgresql://postgres:psgres_db@db-dev:5432/app"
  APP_ENV: "development"