apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev
data:
  # Geändert von "development" auf "local", um Pydantic-Validierung zu erfüllen
  ENVIRONMENT: "local"
  DOMAIN: "localhost"
  
  # Neue Pflichtfelder für das Backend
  PROJECT_NAME: "FastAPI Project Dev"
  FIRST_SUPERUSER: "admin@example.com"
  FIRST_SUPERUSER_PASSWORD: "fastapi_devops_26"
  
  # CORS Einstellungen
  BACKEND_CORS_ORIGINS: "http://localhost:8000,http://localhost,http://localhost:50025"
  
  # Datenbank-Verbindung
  POSTGRES_SERVER: "db-dev"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "app"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "psgres_db"